### ISSUE TITLE
How to create VLANs from within a loop?

### ISSUE THREAD

**Issue by Sneedes** [CiscoDevNet/intersight-ansible#107]
Can I get some guidance on how I can utilize the `cisco.intersight.intersight_rest_api` module to create my list of VLANs from an Ansible loop?

I'm trying to apply something like the following, but _something_ appears to be converting the vlanid from an integer to a string, and the Intersight API cannot handle a string being passed to it.  

```yaml
...
  vars:
    vlans:
      - vlan_id: 11
        vlan_name: VLAN0011-Description
      - vlan_id: 12
        vlan_name: VLAN0012-Description
...


    - name: Create all known VLANs
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        resource_path: /fabric/Vlans
        api_body:
          AutoAllowOnUplinks: true
          EthNetworkPolicy:
            ObjectType: fabric.EthNetworkPolicy
            Moid: "{{ eth_network_policy_moid }}"
          IsNative: false
          MulticastPolicy:
            ObjectType: fabric.MulticastPolicy
            Moid: "{{ multicast_policy_moid }}"
          Name: "{{ item.vlan_name }}"
          PrimaryVlanId: 0
          SharingType: None
          VlanId: "{{ item.vlan_id | int }}"
        query_params:
          $filter: VlanId eq '{{ item.vlan_id | int }}'
      loop: "{{ vlans }}"`

**Comment by Sneedes** [comment]
Here's noting from the module invocation that vlan_id 12, although is originally declared as an integer, when passed to the **VlanId** parameter within the **api_body** variable...something such as Jinja is converting this to a string.
```
failed: [localhost] (item={'vlan_id': 12, 'vlan_name': 'VLAN0012-Description'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_body": {
                "AutoAllowOnUplinks": true,
                "EthNetworkPolicy": {
                    "Moid": "658d4ceb6f62693101dd676b",
                    "ObjectType": "fabric.EthNetworkPolicy"
                },
                "IsNative": false,
                "MulticastPolicy": {
                    "Moid": "659dc8366f626931012ad79c",
                    "ObjectType": "fabric.MulticastPolicy"
                },
                "Name": "VLAN0012-Description",
                "PrimaryVlanId": 0,
                "SharingType": "None",
                **"VlanId": "12"**
            },
            "api_key_id": "638a10b07564612d33073d4a/638a10b07564612d33073d4f/63c188597564612d31e2b069",
            "api_private_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_uri": "https://intersight.com/api/v1",
            "list_body": null,
            "query_params": {
                "$filter": "VlanId eq '12'"
            },
            "resource_path": "/fabric/Vlans",
            "return_list": false,
            "state": "present",
            "update_method": "patch",
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "item": {
        "vlan_id": 12,
        "vlan_name": "VLAN0012-Description"
    },
    "msg": "API error: (400, 'HTTP Error 400: Bad Request', b'{\"code\":\"InvalidRequest\",\"message\":\"Cannot execute the request. The JSON document is malformed.\",\"messageId\":\"barcelona_request_malformed_json\",\"traceId\":\"O2femsmjMDC3-xxxxxxx-xxxxx==\",\"cause\":{\"code\":\"InternalServerError\",\"message\":\"Cannot execute the request due to an error. Retry later.\",\"messageId\":\"barcelona_request_internal_error\",\"traceId\":\"O2femsmjMDC3-xxxxxx-xxxx==\"}}') "
}
```

**Comment by dsoper2** [comment]
You can set jinja2_native=True in the [defaults] section of your ansible.cfg or set the environment variable ANSIBLE_JINJA2_NATIVE=True so that jinja preserves types during templating.  More details are at https://docs.ansible.com/ansible/latest/reference_appendices/config.html

**Comment by Sneedes** [comment]
I can get this to work by setting in an ansible.cfg file in the project root.  
```
$ cat ansible.cfg 
[defaults]
jinja2_native = true
```

I can get this to work by setting an ANSIBLE_JINJA2_NATIVE environment variable when running the playbook.
`$ ANSIBLE_JINJA2_NATIVE=true ansible-playbook vlan_test_2.yml
`

As I'll eventually be running this from Ansible Automation Platform/Ansible Tower...I'd like to avoid complexity about working with overriding ansible.cfg and/or environment variables from the container/execution environment.  

Per the Ansible docs, I believe I should be able to leverage the `environment` keyword at the play, block, or task (preferred) level?

Any usage of ANSIBLE_JINJA_NATIVE `environment` keywords at the playbook or task level don't seem to be working for me.  Am I doing something wrong?

**Comment by dsoper2** [comment]
Here's a link on passing environment variables with Tower: https://access.redhat.com/solutions/3065001.  In case that link isn't accessible, here's the resolution text:
The setting can be found under "Configure Tower >Jobs [tab]" under "Extra Environment Variables". The field expects JSON input and does not require a restart of services to apply

Here's an example:
{
  "VARIABLE_NAME_TO_EXPORT": "value to export",
  "ANSIBLE_DEBUG": "1"
}

**Comment by Sneedes** [comment]
Thanks for the follow-up.

Can close the issue.  Proceeding with a custom `ansible.cfg` file in the template/project root directory.
