### ISSUE TITLE
Version 2.0.18 missing changes

### ISSUE THREAD

**Issue by jeisenbath** [CiscoDevNet/intersight-ansible#141]
I updated to version 2.0.18, but the collection release tar.gz looks like its missing the changes made in #139 to intersight_server_profile.

**Comment by dsoper2** [comment]
Not sure how I managed that.  I've posted a new 2.0.19 collection and verified that the updated modules are there and showing correctly in the code and docs:
ansible-doc cisco.intersight.intersight_server_profile
...
- ldap_policy
        Name of LDAP Policy to associate with this profile.
        default: null
        type: str
