### ISSUE TITLE
Ability to encrypt private key with ansible-vault

### ISSUE THREAD

**Issue by MallocArray** [CiscoDevNet/intersight-ansible#41]
I plan on keeping the private key in an git repo and I currently have the api_key_id string encrypted, but the api_private_key parameter isn't accepting the actual content of the key, but only a path to the file. This means I'm not able to just simply use ansible-vault to encrypt the contents of they key file and have Ansible decrypt it on the fly, as what the module is looking for is just a path.

Could there be another parameter for the actual key value so it could be decrypted and passed directly to the parameter or is there another existing way to secure this file?

**Comment by MallocArray** [comment]
Thank you. This appears to be working if I modify intersight.py to match the version in the repo.  Any idea when these changes will be push to galaxy to be downloaded through that interface?

**Comment by dsoper2** [comment]
Forgot that step - galaxy has been updated with the changes.
