### ISSUE TITLE
Is the return list from intersight_info limits to 1000 members?

### ISSUE THREAD

**Issue by siukwok** [CiscoDevNet/intersight-ansible#62]
- cisco.intersight.intersight_info:
            <<: *api_info
            server_names: 
          register: all_results

The return list (all_results) from cisco.intersight.intersight_info is limited to 1000, is that true?
[Intersight]$ grep -c AccountMoid  all_results.txt
1000

If true, how can I increase the limitation as we have more than 1000 servers registered in Intersight.

**Comment by dsoper2** [comment]
Correct that intersight_info is limited to 1000 servers ($top=1000 which is the max supported by the API).  There's an example with the intersight_rest_api module at https://github.com/CiscoDevNet/intersight-ansible/blob/master/playbooks/update_standalone_inventory.yml that gets all servers by 1st getting the count then paging through all results using top and skip query params.

**Comment by siukwok** [comment]
Hi David,

Thanks for your reply. Found out the limitation from
https://www.intersight.com/apidoc yesterday. Have a good weekend.

Kwok

On Fri, Jun 24, 2022 at 2:50 PM David Soper ***@***.***>
wrote:

> Correct that intersight_info is limited to 1000 servers ($top=1000 which
> is the max supported by the API). There's an example with the
> intersight_rest_api module at
> https://github.com/CiscoDevNet/intersight-ansible/blob/master/playbooks/update_standalone_inventory.yml
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CiscoDevNet_intersight-2Dansible_blob_master_playbooks_update-5Fstandalone-5Finventory.yml&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=vGe0saWvbUTkyjwPHLoqx2u3DVXF8hozkMUA1SdFltk&m=ErHcXEVE2rDP6RtUQ7ZEzBnGQVK3eFLizCAYRJSPcBNh0tDDsXK0t2BHgX_EQ1I9&s=UItemNh6Vrm55UFcrHMNMqniJ_H_1qXLDrwqT4cP46E&e=>
> that gets all servers by 1st getting the count then paging through all
> results using top and skip query params.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CiscoDevNet_intersight-2Dansible_issues_62-23issuecomment-2D1165888116&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=vGe0saWvbUTkyjwPHLoqx2u3DVXF8hozkMUA1SdFltk&m=ErHcXEVE2rDP6RtUQ7ZEzBnGQVK3eFLizCAYRJSPcBNh0tDDsXK0t2BHgX_EQ1I9&s=FPev5BD6vaS73moIIGQrrszYZx7YWd_ZRuxs_Rqa7ao&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZTZB65BALMY4JP3WPUSANDVQYGQLANCNFSM5ZKLC3RQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=vGe0saWvbUTkyjwPHLoqx2u3DVXF8hozkMUA1SdFltk&m=ErHcXEVE2rDP6RtUQ7ZEzBnGQVK3eFLizCAYRJSPcBNh0tDDsXK0t2BHgX_EQ1I9&s=aSAE3X5OXymbRMcS5v44iv_kZOSnO75Mgq0snUieqjc&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Kwok (Sunny) Siu
System Administration
Network Data Centers
Network Systems
Verizon
Office: (682) 831-3615
Mobile: (817) 320-1074
