### ISSUE TITLE
Using intersight_rest_api module and getting error for api key

### ISSUE THREAD

**Issue by sat1121** [CiscoDevNet/intersight-ansible#65]
I am trying to use the intersight_rest_api module and when i am trying to pass the api_private_key variable as a string which was encrypted using ansible vault. But i am getting an error message that is indicating that the module is considering the key as a file name not a string. Below is the reference of the error message. According to the document the var accepts both file name and string as accepted value. Any thoughts on how to have the api_private_key variable passed as a vault encrypted string rather than a file reference?

If i save the key in a file as plain text and reference that it works. But we need to store the private key in an encrypted format. 

In the below example "intersight_api_key" variable is saved as a group var and i can confirm that it is returning the key after decrypting with a debug task. Just the module doesn't seem to see it as a string reference but sees it as a file name.

Error message

The error was: OSError: [Errno 63] File name too long: '-----BEGIN RSA PRIVATE KEY

Playbook reference

    - name: uri call to intersight
      intersight_rest_api:
        api_private_key: "{{ intersight_api_key }}"
        api_key_id: "{{ intersight_api_key_id }}"
        resource_path: /vnic/EthIfs
        query_params:
          $filter: "Profile.Moid eq '<some_moid>'"
        validate_certs: false

**Comment by dsoper2** [comment]
There's an example of using vault and the secret key as a string at https://github.com/CiscoDevNet/intersight-ansible/blob/main/playbooks/vault_intersight_server_profile.yml.  I verified the string based param is working in our environment:

ansible-playbook -i tme-demo_profile_inventory --vault-id tme@vault_password_file vault_intersight_server_profile.yml -vvv
ok: [SP-SJC07-R14-FI-1-1-6 -> localhost] => {
    "changed": false,
    "intersight_servers": [],
    "invocation": {
        "module_args": {
            "api_private_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",

I am using v3 API keys - there may be an issue with v2 keys and the filename check that I'll test.  Ahead of any fixes for v2 keys v3 keys should work.

**Comment by dsoper2** [comment]
I've fixed using v2 private keys as strings and published cisco.intersight 1.0.21.

ansible-galaxy collection list

# /Users/dsoper/.ansible/collections/ansible_collections
Collection                                   Version
-------------------------------------------- -------
...
cisco.intersight                             1.0.21

I've tested with v2 and v3 keys in our environment and both are now working.
