### ISSUE TITLE
1.0.5 build broken

### ISSUE THREAD

**Issue by gundalow** [CiscoDevNet/intersight-ansible#9]
mkdir /tmp/aaaa
ansible-galaxy -vvvv collection install -p /tmp/aaaa cisco.intersight

```
starting collection install process
Installing 'cisco.intersight:1.0.5' to '/tmp/aaaa/ansible_collections/cisco/intersight'
Downloading https://galaxy.ansible.com/download/cisco-intersight-1.0.5.tar.gz to /home/johnb/.ansible/tmp/ansible-local-30145IzOdo0/tmpZoKgn4
Validating downloaded file hash 01fd1a3734cc16d83f3ce31b5b3c6996524c07289fd233fa413d9fd9e5ed59b4 with expected hash 01fd1a3734cc16d83f3ce31b5b3c6996524c07289fd233fa413d9fd9e5ed59b4
ERROR! Collection tar at '/home/johnb/.ansible/tmp/ansible-local-30145IzOdo0/tmpZoKgn4/cisco-intersight-1.0.5.tarSpxzFZ.gz' does not contain the expected file 'releases/cisco-intersight-1.0.4.tar.gz'.
```

**Comment by gundalow** [comment]
Also the galaxy.yml file in this repo still says `1.0.4`, and I don't see any Git Tags for the releases

**Comment by gundalow** [comment]
This appears to still be broken.

**Comment by dsoper2** [comment]
1.0.8 release with release tag and build appears to work:
$ ansible-galaxy collection install cisco.intersight --force
Process install dependency map
Starting collection install process
Installing 'cisco.intersight:1.0.8' to '/Users/dsoper/.ansible/collections/ansible_collections/cisco/intersight'
